env:
  browser: true
  es6: true
  node: true
extends:
  - airbnb
  - eslint:recommended
  - plugin:react/recommended
  - airbnb/hooks
  - some-other-config-you-use
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  React: writable
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - import
rules:
  class-methods-use-this: 1
  import/no-cycle: 0
  implicit-arrow-linebreak: 0
  react/no-array-index-key: 0
  react/react-in-jsx-scope: 0
  jsx-a11y/anchor-is-valid: 0
  import/prefer-default-export: 0
  import/no-unresolved: 0
  react/jsx-props-no-spreading: 0
  react/prop-types: 0
  import/no-extraneous-dependencies: 0
  jsx-a11y/label-has-associated-control:
    - 2
    - required:
        some:
          - nesting
          - id
  react/jsx-filename-extension:
    - 1
    - extensions:
        - '.js'
        - '.jsx'
  indent:
    - 2
    - 2
  linebreak-style:
    - 0
    - error
    - windows
  quotes:
    - 2
    - single
    - avoidEscape: true
  semi:
    - error
    - never
  arrow-parens:
    - error
    - as-needed
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
